version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://bazi_user:${MONGO_PASSWORD}@mongodb:27017/bazi?authSource=admin
      - NEXT_PUBLIC_BASE_URL=https://bazi.1895.cn
      - DB_AUTO_CONNECT=true
      - DB_MAX_RETRIES=5
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bazi_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bazi_user
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - bazi_network
    command: ["--auth"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin -u bazi_user -p "${MONGO_PASSWORD}" --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  backup:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db:ro
      - ./backups:/backups
    networks:
      - bazi_network
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint: |
      bash -c 'echo "创建备份目录"; mkdir -p /backups;
      echo "每天凌晨3点自动备份数据库";
      while true; do
        current_date=`date +%Y%m%d-%H%M`;
        echo "[$current_date] 备份数据库...";
        mongodump --host mongodb --port 27017 -u bazi_user -p ${MONGO_PASSWORD} --authenticationDatabase admin --db bazi --out /backups/backup-$current_date;
        echo "备份完成，保留最近10个备份";
        ls -tp /backups | grep -v / | tail -n +11 | xargs -I {} rm -- /backups/{};
        echo "下次备份将在24小时后执行";
        sleep 86400;
      done'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

networks:
  bazi_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 